feat: Add Getting Started page
redhat-developer/intellij-openshift-connector pull request #480
Opened 2022-11-21 09:43 UTC by jeffmaury

Fixes #435
Fixes #479

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

## What is the purpose of this change? What does it change?

## Was the change discussed in an issue?
fixes #???

## How to test changes?

2022-11-22 09:24 UTC, lstocchi approved these changes
LGTM, just a typo and missing spaces

2022-11-22 09:24 UTC, lstocchi commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                        "application in a continuous workflow. It continuously watches teh directory for any new " +
typo `teh`

2022-11-22 09:24 UTC, lstocchi commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                "<html><p>Start the component in debug mode. The devfile.yaml should be specified with the" +
no space at the end of the row so you see `thedebug` in the IDE

2022-11-22 09:42 UTC, sbouchet requested changes
please fix the typos.
also, the devfile registry gif might look better :
- by removing the top pixels that are disturbing
- by removing/cropping the loading times

2022-11-22 09:42 UTC, sbouchet commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                "<html><p>This is inner loop development and allows you to code, build, run and test the" +
```suggestion
                "<html><p>This is inner loop development and allows you to code, build, run and test the  " +
```

2022-11-22 09:42 UTC, sbouchet commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                        "application in a continuous workflow. It continuously watches teh directory for any new " +
```suggestion
                        "application in a continuous workflow. It continuously watches the directory for any new " +
```

2022-11-22 09:42 UTC, sbouchet commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                "<html><p>Start the component in debug mode. The devfile.yaml should be specified with the" +
```suggestion
                "<html><p>Start the component in debug mode. The devfile.yaml should be specified with the " +
```

2022-11-24 12:39 UTC, mohitsuman commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                "associated 'devfile.yaml' configuration. Devfile is a manifest file that contains information about " +
```suggestion
                "associated 'devfile.yaml' configuration. With devfiles, you record the instructions for configuring and running your build environment as a YAML-formatted text file and provide Build, Run and Deployment information within the file." +
```

2022-11-24 12:39 UTC, mohitsuman commented on src/main/java/org/jboss/tools/intellij/openshift/GettingStartedToolWindow.java
> +                "various resources (URL, Storage, Services, etc.) that correspond to your component</p></html>",
```suggestion
                "</p></html>",
```

2022-11-24 12:44 UTC, mohitsuman requested changes
Few wording changes.

2022-11-24 19:24 UTC, mohitsuman approved these changes
LGTM

2022-11-25 07:10 UTC, merged