chore: prepare 1.7.0
redhat-developer/intellij-openshift-connector pull request #629
Opened 2023-12-01 08:50 UTC by sbouchet

## What is the purpose of this change? What does it change?
prepare 1.7.0

## Was the change discussed in an issue?

## How to test changes?

2023-12-01 13:50 UTC, mohitsuman commented on README.md
> +Below a small demo using Heml stable repo (https://charts.helm.sh/stable) and installing kuberos chart.
```suggestion
Below is a small demo of the workflow: installing `kuberos` chart from the Helm stable repo (https://charts.helm.sh/stable) 
```

2023-12-01 13:51 UTC, mohitsuman commented on README.md
> +There is no need to install anything prior to use Helm. By default if there is no repository configured, the openshift
```suggestion
There is no need to install anything prior to use Helm. By default if there is no repository configured, the OpenShift
```

2023-12-01 13:51 UTC, mohitsuman commented on README.md
> +helm repository will be use (https://charts.openshift.io/).
```suggestion
Helm repository will be used (https://charts.openshift.io/).
```

2023-12-01 13:52 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
> +  <li>Added an action to install Helms Charts in cluster</li>
```suggestion
  <li>Added an action to install Helm Charts in the connected cluster</li>
```

2023-12-01 13:53 UTC, mohitsuman requested changes
Typos and wording fixes

2023-12-04 10:23 UTC, sbouchet commented
/hold

2023-12-05 10:05 UTC, adietish approved these changes

2023-12-06 10:21 UTC, sbouchet commented
/override ci/prow/e2e-4.11

2023-12-06 10:35 UTC, sbouchet commented
/unhold

2023-12-06 10:36 UTC, merged