chore(skip-release): Prepare 1.9.0
redhat-developer/intellij-openshift-connector pull request #786
Opened 2024-04-15 13:14 UTC by sbouchet

## What is the purpose of this change? What does it change?

## Was the change discussed in an issue?
fixes #784 

## How to test changes?

2024-04-16 14:39 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
> +  <li>Bug fixes</li>
```suggestion
  <li>Improvements around `start` and `stop` for OpenShift components</li>
```

2024-04-16 14:39 UTC, mohitsuman requested changes
wording changes

2024-04-18 11:05 UTC, adietish approved these changes
lgtm

2024-04-18 12:19 UTC, adietish commented
/override ci/prow/e2e-openshift

2024-04-18 12:23 UTC, merged